#!/usr/bin/env ruby

require 'minitest/autorun'

class Game
  def self.get_next_generation_from grid
    if grid.include? '*'
      grid.sub! '*', '.'
    else
      grid
    end
  end
end

describe "when given an empty grid" do
  it "should return the same grid" do
    input_grid = <<-ENDGRID
........
........
........
........
ENDGRID

    expected_grid = <<-ENDGRID
........
........
........
........
ENDGRID
    result_grid = Game.get_next_generation_from input_grid
    result_grid.must_equal expected_grid
  end
end

describe "when given a grid with only one cell" do
  it "should return an empty grid" do
    input_grid = <<-ENDGRID
........
....*...
........
........
ENDGRID

    expected_grid = <<-ENDGRID
........
........
........
........
ENDGRID
    result_grid = Game.get_next_generation_from input_grid
    result_grid.must_equal expected_grid
  end
end
